# environment for performing the napari spot detection tutorial
# install: conda env create -f environment.yaml
# update:  conda env update -f environment.yaml

name: napari-tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - notebook
  - pip
  - pip:
    - cookiecutter
    - napari[all]
    - stardist-napari
    - numpy
    - scikit-image
    - scipy